#!/usr/local/bin/node
let urllib = require('urllib');
let Phrase = require("mhartl-palindrome");
let url = 'https://cdn.learnenough.com/phrases.txt'

urllib.request(url, { followRedirect: true}, function(err, data, res){
  if(err){
    throw err; // you need to handel error
  }
  let body = data.toString();
  let lines = body.split("\n");
  let plaindromes = lines.filter(line => new Phrase(line));
  plaindromes.forEach(function(palindrome){
    console.log("palindrome detected:", palindrome);
  })
});