#!/usr/local/bin/node

//returns the paragraph from a Wikipedia link, stripped of reference numbers.
let urllib = require("urllib");
let url = process.argv[2];

if (!url){
  console.log("No URL found!");
  process.exit();
}

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

urllib.request(url, { followRedirect: true }, function(error, data, response){
  let body = data.toString();
  // Simulate a Document Object Model.
  let { document } = (new JSDOM(body)).window;

  // Grab all the paragraph and references.
  let paragraphs = document.querySelectorAll("p");
  let refernces =  document.querySelectorAll(".reference");

  //Remove any refernces.
  refernces.forEach(function(reference){
    reference.remove();
  })

  // Print out all of the paragraphs.
  paragraphs.forEach(function(paragraph){
    console.log(paragraph.textContent);
  });
});